updated code to run with Python 3
dimagi/outlier-detect pull request #1
Opened 2021-03-17 19:08 UTC by faisalmlalani

@bderenzi ready for review!

2021-03-17 20:57 UTC, bderenzi requested changes
Looks good. One small fix on the module stuff, but once that's sorted we're good to go, I think

2021-03-17 20:57 UTC, bderenzi commented on outlierdetect/__init__.py
> +# from outlierdetect import run_sva, run_mma, __doc__
This is not the correct solution. More details here:

https://docs.python.org/3/reference/import.html#regular-packages

Correct code should be:
```python
from .outlierdetect import run_sva, __doc__
# run_mma will be missing when stats are not available
try:
    from .outlierdetect import run_mma
except ImportError:
    pass
```

I've tested this on 3.8.6 and 2.7 and it works on both

2021-03-17 20:57 UTC, bderenzi commented on example.py
> +from outlierdetect import outlierdetect
Can revert once the change is made to `__init__.py`

2021-03-17 22:42 UTC, faisalmlalani commented
@bderenzi fixed!

2021-03-18 06:52 UTC, bderenzi approved these changes
Looks good -- thanks

2021-03-19 19:15 UTC, merged